### ISSUE TITLE
Favor ajustar dois imports em index.tsx

### ISSUE THREAD

**Issue by acenelio** [kleberlimaGit/git-user-seach#1]
Favor fazer uma pequena correção nos imports de user e formatarData em index.tsx. Está dando erro por causa de maiúsculas/minúsculas:

![case](https://user-images.githubusercontent.com/13897257/98824957-b1724780-2412-11eb-9b01-a1807f75e3b7.png)

**Comment by kleberlimaGit** [comment]
Ok professor ja foi alterado, não entendi pq não subiu essa alteração pro git. mas ta tudo ok agora
